stbt run: Fix UnicodeEncodeError from unicode exception messages
THIS INTRODUCES A BREAKING CHANGE (see below).

Since 5af690e (released in stb-tester v22) you can `print` unicode
strings to a log file, but you still couldn't raise an exception with
unicode characters in the exception message. Now you can.

The first change in `stbt-run` fixes this error:

    Traceback (most recent call last):
      File "stbt-run", line 108, in <module>
        error_message = str(e)
    UnicodeEncodeError: 'ascii' codec can't encode character ...

The second change fixes the following error:

    Traceback (most recent call last):
      File "stbt-run", line 116, in <module>
        traceback.print_exc(file=sys.stderr)
      File "/usr/lib/python2.7/traceback.py", line 233, in print_exc
        print_exception(etype, value, tb, limit, file)
      File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
        print_tb(tb, limit, file)
      File "/usr/lib/python2.7/traceback.py", line 70, in print_tb
        if line: _print(file, '    ' + line.strip())
      File "/usr/lib/python2.7/traceback.py", line 13, in _print
        file.write(str+terminator)
      File "/usr/lib/python2.7/codecs.py", line 351, in write
        data, consumed = self.encode(object, self.errors)
    UnicodeDecodeError: 'ascii' codec can't decode ...

It was happening because earlier in `stbt-run` we set `sys.stderr =
codecs.getwriter('utf8')(sys.stderr)`, so `traceback.print_exc` was
trying to utf8-encode the line from the source file to print it in
the backtrace, but python's internal `linecache` module already
had it in utf8-encoded form.

BREAKING CHANGE: If you previously used unicode characters in your
exception messages, like either of these two examples:

    raise RuntimeError(u"ünicode".encode("utf-8"))
    assert False, u"ünicode".encode("utf-8")

...then you will need to remove the `.encode("utf-8")`, or you will
get a UnicodeDecodeError from `stbt run`.